### ISSUE TITLE
Add ability to suppress symbol resolution

### ISSUE THREAD

**Issue by qdzo** [zen-lang/zen#19]
Problem: 

Sometimes it's usefull to place some 'code like' DSL inside zen definitions. 

Example

```
{:zen/tags #{extract}
:extract {:patient-name (get-in [:name :given 0])
               :user-id (dsl/ctx :user)}}
```
But every symbol needs to be resolved and zen will fail in loading ns with sutch definitions.

Potentially we can get around this problem by writing empty symbol definitions, 

But in the long run it's not an good solution.

**Comment by carbon-hvze** [comment]
related to #20

**Comment by carbon-hvze** [comment]
@qdzo symbol expansion in lists is now disabled by default
your lisp should work ok and you can get rid of namespace prefixes for symbols
