### ISSUE TITLE
implement zen expression types

### ISSUE THREAD

**Issue by niquola** [zen-lang/zen#20]

**Comment by niquola** [comment]
Do not validation lists?

**Comment by carbon-hvze** [comment]
feature sketch:

- symbols in list are not expanded by default
- vector-like validations continue to work on list type
- engine may be provided that dispatches to the eval-apply impl
- default :clj engine is supported

**Comment by carbon-hvze** [comment]
as of right now we stopped on the symbol resolution part, maybe will implement macro-engine later as a separate feature
