### ISSUE TITLE
Zen *key words* should be keywords instead of symbols

### ISSUE THREAD

**Issue by KGOH** [zen-lang/zen#23]
There are few reserved symbols in zen namespaces: `ns`, `import` and `alias`
Because of this user can not define own schemas with these names. Frequent use-case looks like this:
```edn
{ns my-operations
 
 export {:zen/tags #{my-op}}
 import {:zen/tags #{my-op}}}
```

Zen will return error that a `#{}` expected as a value of `import` since it is used to resolve namespace deps.

Probably `ns`, `import` and `alias` should be keywords like `:zen/tags`, and user definitions would be any symbol e.g.:
```edn
{:zen/ns my-operations
 :zen/import #{my-deps}
 
 export {:zen/tags #{my-op}}
 import {:zen/tags #{my-op}}}
```

Urgency: low
This is a minor inconvenience for me, but it looks like a language design flaw

**Comment by carbon-hvze** [comment]
with this commit global :ns and :import (as keywords, not symbols) are supported. probably I will also implement :alias in the same fashion

**Comment by carbon-hvze** [comment]
:alias keyword is implemented
